```{r}
# counting duration
start_time <- Sys.time()


#install.packages(future)
library(future)
# check the current active plan
plan()
plan("multisession", workers = 8)
options(future.globals.maxSize = 50 * 1024^3)
```

```{r}
library(Seurat)
library(dplyr)
library(Matrix)
library(gdata)
library(patchwork)
library(ggplot2)
library(cowplot)


#Define your working directory path
dirname <- '/Users/nagai/Documents/single_cell_celegans/'

# Parameters load file
source(paste0(dirname,'script/parameters_L2.txt'))

# Output plot file
#postscript(paste0(dirname, 'plots.ps'), horizontal=T)
#op <- par(cex=1.2)
#par(cex.axis=2, cex.lab=1, cex.main=1.2, cex.sub=1)

# Pre-process Seurat Object
### STEP1: Read in 10X Cell Ranger matrix and create Seurat object
counts_matrix_filename = paste0(dirname, 'data_L2')
CR <- Read10X(data.dir = counts_matrix_filename)

# Metrics
#dim(counts)
#object.size(counts) # size in bytes
#object.size(as.matrix(counts)) # size in bytes


## Seurat Object creation
S1 <- CreateSeuratObject(counts = CR, project = proj_name
                            , assay='RNA'
                            , min.cells = qtd_min_cells
                            , min.features = qtd_min_features)

# mitochondrial gene list
mt_gene_list = c('nduo-6', 'atp-6', 'nduo-2', 'ctb-1', 'ctc-3', 'nduo-4', 'ctc-1', 'ctc-2','nduo-3', 'nduo-5')
mt_gene_list

#check if mitochondrial genes are in the matrix
all(mt_gene_list %in% rownames(S1))

S1 <- PercentageFeatureSet(object=S1 , features=mt_gene_list, col.name='Percent_MT')

######## Collect metrics?
metrics <- TRUE

if (metrics) {
    # Data metrics collection
    counts_per_cell <- Matrix::colSums(CR)
    counts_per_gene <- Matrix::rowSums(CR)
    genes_per_cell <- Matrix::colSums(CR>0)
    cells_per_gene <- Matrix::rowSums(CR>0) # only count cells where the gene is expressed

    # Data metrics plots
    p1 <- hist(log10(counts_per_cell+1),main='counts per cell',col=colorplots)
    p2 <- hist(log10(genes_per_cell+1), main='genes per cell', col=colorplots)
    p3 <- plot(counts_per_cell, genes_per_cell, log='xy', col=colorplots)+title('counts vs genes per cell')
    p4 <- hist(log10(counts_per_gene+1), main='counts per gene', col=colorplots)
    p5 <- plot(sort(genes_per_cell), xlab='cell', log='y', main='genes per cell (ordered)')
    p6 <- VlnPlot(S1, features = c('nFeature_RNA', 'nCount_RNA', 'Percent_MT'), ncol = 3, pt.size=0.2, log=T)

    # Capture abnormal cells
    APOPT_S1 <- FeatureScatter(S1, feature1 = 'nCount_RNA', feature2 = 'Percent_MT', pt.size=0.4, cols=colorplots)+NoLegend()

    DLET_S1 <- FeatureScatter(S1, feature1 = 'nCount_RNA', feature2 = 'nFeature_RNA', pt.size=0.4, cols=colorplots)+NoLegend()


    ########## DATA metrics PLOTS

    # Histogram of counts per cell
    # Histogram pf genes per cell
    lbl <- c( 'Counts per cell', 'Number of genes per cell' )
    plot_grid(
                p1,p2
                ,labels=lbl
                ,label_size= 12
                ,nrow=1, ncol=2
    )


    # Scatter counts per gene per cell
    p3

    # Histogram Log10 counts per gene
    p4

    # Number of genes per cell ordered
    p5

    # Violin plot
    p6

    APOPT_S1

    DLET_S1

    #FREE memory
    remove(p1,p2,p3,p4,p5,p6, APOPT_S1, DLET_S1)
    remove(CR)
}


# Summary (attributes(S1))
attr(S1, 'assays')$RNA

```


```{r}
### STEP2: Filtering unwanted cells
S2 <- subset(S1, subset = nFeature_RNA > min_nFeature_RNA & nFeature_RNA < max_nFeature_RNA & nCount_RNA < 50000 & Percent_MT < max_perc_mt)


# Apoptosis
#p9 <- FeatureScatter(S2, feature1 = 'nCount_RNA', feature2 = 'Percent_MT', pt.size=0.5, cols=colorplots)+NoLegend()

# Droplets
#p10 <- FeatureScatter(S2, feature1 = 'nCount_RNA', feature2 = 'nFeature_RNA', pt.size=0.5, cols=colorplots)+NoLegend()

# Summary (attributes(S2))
attr(S2, 'assays')$RNA

# Free memory
remove(S1)

```


```{r}
### STEP3: Pre-process Seurat Object
#3.1 Normalization
S3 <- NormalizeData(S2, normalization.method='LogNormalize', scale.factor = norm_scale, verbose=FALSE)

#3.2 Selecting variable genes
S3 <- FindVariableFeatures(S3, selection.method = 'vst', nfeatures = nFeatures_var, verbose=FALSE)

#3.3 Scaling
all.genes <- rownames(S3)
S3 <- ScaleData(S3, vars.to.regress='Percent_MT', features = all.genes, verbose=FALSE)

# Identify the N most highly variable genes
topN <- head(VariableFeatures(S3), topx)

# plot variable features with and without labels
p11 <- VariableFeaturePlot(S3)
p12 <- LabelPoints(plot = p11, points = topN, repel = TRUE, xnudge=0, ynudge=0)
```


```{r}
# PCA with nVF
S3 <- RunPCA(S3, features = VariableFeatures(object = S3)
            , ndims.print=1:3
            , nfeatures.print=5
            , npcs=nPCS
            , verbose=FALSE)

# Define number of PCs to consider
#PCx <- length(attributes(S3[['pca']])$stdev) #automatically
PCx <- 30 #visually decided

# Summary
summary(attributes(S3[['pca']]))
S3 <- JackStraw(S3, dims=PCx, num.replicate=100, verbose=FALSE)
S3 <- ScoreJackStraw(S3, dims=1:PCx)
p13 <- JackStrawPlot(S3, dims=1:PCx, reduction='pca')
p14 <- ElbowPlot(S3, ndims=nPCS, reduction='pca')

# UMAP: Uniform Manifold Approximation and Projection for Dimension Reduction
S3 <- RunUMAP(S3, dims=1:PCx, verbose=FALSE)
S3 <- RunTSNE(S3, dims=1:PCx)

## Clustering based on PCA distance
S3 <- FindNeighbors(S3, dims=1:PCx, verbose=FALSE)
S3 <- FindClusters(S3, resolution = RES, verbose=FALSE)
```

```{r}
# Find markers for every cluster compared to all remaining cells.
# logFC >0; highly expressed at the 1st group
# p_val_adj; bonferroni correction
# pct1.; percentage of cells where the gene is detected in the 1st group
# pct2.; percentage of cells where the gene is detercted in the 2nd group
S3.markers <- FindAllMarkers(S3, only.pos=TRUE
                            ,min.pct=0.25
                            ,test.use='wilcox'
                            ,logfc.threshold=logFC
                            ,return.thres=0.01
                            ,min.cells.feature=qtd_min_cells
                            ,min.cells.group=qtd_min_cells)
idx <-S3.markers[, 'p_val_adj'] < qvThres
S3.markers <- S3.markers[idx,]
#S3.markers
#
a <- S3.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_logFC)
a

# Visualizing marker expression

markers1 <- c("cnpa-2","unc-54","pgl-1","ppw-2","ram-2","col-107")
markers2 <- c("egl-3","cla-1","T2B11.3","ZK822.4","hlh-1","myo-3")
markers3 <- c("hlh-8","ttx-1","irg-7","elt-1","aff-1","ceh-32","gbb-1")



VlnPlot(S3, features = markers1)
VlnPlot(S3, features = markers2)
VlnPlot(S3, features = markers3)
#VlnPlot(S3, features = S3.markers)


VlnPlot(S3, features = markers1 , slot = "counts", log = TRUE)
VlnPlot(S3, features = markers2 , slot = "counts", log = TRUE)
VlnPlot(S3, features = markers3 , slot = "counts", log = TRUE)


FeaturePlot(S3, features = markers1, reduction = "tsne")
FeaturePlot(S3, features = markers2, reduction = "tsne")
FeaturePlot(S3, features = markers3, reduction = "tsne")

#new.cluster.ids <- c("Naive CD4 T", "Memory CD4 T", "CD14+ Mono", "B", "CD8 T", "FCGR3A+ Mono","NK", "DC", "Platelet")
#names(new.cluster.ids) <- levels(S3)
#S3 <- RenameIdents(S3, new.cluster.ids)
#DimPlot(S3, reduction = "tsne", label = TRUE, pt.size = 0.5) + NoLegend()






# Store current Seurat3 object
save(S3, file=paste0(dirname, 'S3.RData'))
save(S3.markers, file=paste0(dirname, 'S3.makers.RData'))

```





```{r}
#----------------------- Plots


#p7
#p8
#p9
#p10
#p11
p12 # variablefeatureplots
p13 # jackstrawplot
p14 # Elbowplot

# After clustering

#p15 <- FeatureScatter(S3, feature1 = 'nCount_RNA', feature2 = 'Percent_MT', pt.size=0.2, cols=colorplots)
#p16 <- FeatureScatter(S3, feature1 = 'nCount_RNA', feature2 = 'nFeature_RNA', pt.size=0.2, cols=colorplots)


p17 <- DimPlot(S3, reduction='pca', label=TRUE, pt.size=0.5, label.size=6)+ggtitle(label='PCA')
p18 <- DimPlot(S3, reduction='umap', label=TRUE, pt.size=0.5, label.size=6)+ggtitle(label='UMAP')
p19 <- DimPlot(S3, reduction='tsne', label=TRUE, pt.size=0.5, label.size=6)+ggtitle(label='TSNE')

#p15 # featurescatter('ncount_rna, percent_mt')
#p16 # featurescatter('ncount_rna, nfeature_rna')
p17 # dimplot('PCA')
p18 # dimplot('umap')
p19 # dimplot('tsne')

dev.off()


#remove(p7)
#remove(p8)
#remove(p9)
#remove(p10)
#remove(p11)
remove(p12)
remove(p13)
remove(p14)
remove(p15)
remove(p16)
remove(p17)
remove(p18)
remove(p19)


remove(S3)
remove(S3.markers)


end_time <- Sys.time()
end_time - start_time

#q()
```




